version: "3.9"

services:
  db:
    build: .
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: pc_komponenty  
    volumes:
      - /opt/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  adminer:
    image: adminer:latest 
    container_name: adminer_db
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db


